-- CREACIÓN DEL LOGIN GCM
CREATE USER GCM WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'GCM';

COMMENT ON ROLE GCM IS 'LOGIN DE LA PLATAFORMA DE GESTION CATASTRAL MULTIPAIS';

-- CREAMOS LA BASE DE DATOS
CREATE DATABASE "GCM";
 
-- ACTIVAMOS LA BASE DE DATOS QUE ACABAMOS DE CREAR
\c "GCM"

-- LE AÑADIMOS LA EXTENSIÓN POSTGIS
CREATE EXTENSION postgis;

-- Y LA EXTENSIÓN UUID
create extension "uuid-ossp";
 
-- DAMOS PRIVILEGIOS...
GRANT ALL ON geometry_columns TO PUBLIC;
GRANT ALL ON geography_columns TO PUBLIC;
GRANT ALL ON raster_columns TO PUBLIC;
GRANT ALL ON raster_overviews TO PUBLIC;
GRANT ALL ON spatial_ref_sys TO PUBLIC;

-- CREACIÓN DEL ESQUEMA
CREATE SCHEMA GCM AUTHORIZATION GCM;

COMMENT ON SCHEMA GCM IS 'ESQUEMA DE LA PLATAFORMA DE GESTION CATASTRAL MULTIPAIS';

GRANT ALL ON SCHEMA GCM TO GCM;

ALTER DEFAULT PRIVILEGES IN SCHEMA GCM GRANT ALL ON TABLES TO GCM WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA GCM GRANT SELECT, USAGE ON SEQUENCES TO GCM WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA GCM GRANT EXECUTE ON FUNCTIONS TO GCM WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA GCM GRANT USAGE ON TYPES TO GCM WITH GRANT OPTION;

