-----------------------------------------------------------------
-- CREACIÓN DE TABLAS, CLAVES PRIMARIAS E ÍNDICES
-----------------------------------------------------------------
CREATE TABLE GCM.CI_RESPONSABLE_PARTY 
(
  OID character varying(48) NOT NULL 
, INDIVIDUAL_NAME character varying(255) 
, ORGANIZATION_NAME character varying(255) 
, POSITION_NAME character varying(255) 
, ADDRESS character varying(255) 
, EMAIL character varying(255) 
, PHONE_NUMBER character varying(32) 
, FAX_NUMBER character varying(32) 
, ROLE character varying(255) 
, CONSTRAINT CI_RESPONSABLE_PARTY_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.CI_RESPONSABLE_PARTY OWNER TO GCM;

CREATE TABLE GCM.LAG_ADM_SOURCE_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_ADM_SOURCE_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_ADM_SOURCE_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_AVAIL_STATUS_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LA_AVAIL_STATUS_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_AVAIL_STATUS_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_BA_UNIT_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_BA_UNIT_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_BA_UNIT_TYPE OWNER TO GCM;

CREATE TABLE GCM.CI_PRES_FORM_CODE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT CI_PRES_FORM_CODE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.CI_PRES_FORM_CODE OWNER TO GCM;

CREATE TABLE GCM.LAG_RIGHT_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_RIGHT_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_RIGHT_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_BA_UNIT 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, BA_UNIT_TYPE character varying(3) 
, PLACE_NAME character varying(80) 
, SUNIT_ID character varying(48) 
, ADM_USE character varying(3) 
, CONSTRAINT LAG_BA_UNIT_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_BA_UNIT OWNER TO GCM;

CREATE INDEX LAG_BA_UNIT_LOCAL_ID_IX ON GCM.LAG_BA_UNIT (LOCAL_ID);

CREATE TABLE GCM.LAG_ADM_SOURCE 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, DESCRIPTION character varying(255) 
, SOURCE_TYPE character varying(3) 
, TRANSACTION_CODE character varying(80) 
, ACCEPTANCE timestamp without time zone 
, AVAIL_STATUS character varying(3) 
, EXT_ARCHIVE_ID character varying(48) 
, LIFE_SPAN_STAMP timestamp without time zone 
, MAIN_TYPE character varying(3) 
, QUALITY character varying(48) 
, RECORDATION timestamp without time zone 
, SOURCE character varying(48) 
, SUBMISSION timestamp without time zone 
, OFFICIAL SMALLINT DEFAULT 1 
, DOCUMENT bytea 
, CONSTRAINT LAG_ADM_SOURCE_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_ADM_SOURCE OWNER TO GCM;

CREATE INDEX LAG_ADM_SOURCE_LOCAL_ID_IX ON GCM.LAG_ADM_SOURCE (LOCAL_ID);

CREATE TABLE GCM.LAG_RIGHT 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, BAUNIT_ID character varying(48) 
, PARTY_ID character varying(48) 
, SOURCE_ID character varying(48) 
, DESCRIPCION character varying(255) 
, RIGHT_TYPE character varying(3) 
, SHARES double precision 
, SHARE_CHECK smallint DEFAULT 0 
, TIME_SPEC character varying(64) 
, CONSTRAINT LAG_RIGHT_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_RIGHT OWNER TO GCM;

CREATE INDEX LAG_RIGHT_LOCAL_ID_IX ON GCM.LAG_RIGHT (LOCAL_ID);

CREATE TABLE GCM.LAG_CROPS
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, BAUNIT_ID character varying(48) 
, CROP_TYPE character varying(3) 
, AREA double precision 
, ECONOMIC_VALUE double precision 
, CONSTRAINT LAG_CROPS_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_CROPS OWNER TO GCM;

CREATE INDEX LAG_CROPS_ID_IX ON GCM.LAG_CROPS (LOCAL_ID);

CREATE TABLE GCM.LAG_CROPS_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_CROPS_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_CROPS_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_PARTY_ROLE_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_PARTY_ROLE_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_PARTY_ROLE_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_PARTY_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_PARTY_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_PARTY_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_PARTY 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, NAME character varying(255) 
, PARTY_ROLE character varying(3) 
, PARTY_TYPE character varying(3) 
, ADDRESS_ID character varying(48) 
, CONSTRAINT LAG_PARTY_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_PARTY OWNER TO GCM;

CREATE INDEX LAG_BA_PARTY_LOCAL_ID_IX ON GCM.LAG_PARTY (LOCAL_ID);

CREATE TABLE GCM.LAG_GROUP_PARTY 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, GROUP_PARTY_TYPE character varying(3) 
, CONSTRAINT LAG_GROUP_PARTY_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_GROUP_PARTY OWNER TO GCM;

CREATE INDEX LAG_BA_GPARTY_LOCAL_ID_IX ON GCM.LAG_GROUP_PARTY (LOCAL_ID);

CREATE TABLE GCM.LAG_PARTY_MEMBER 
(
  GROUP_ID character varying(48) NOT NULL 
, PARTY_ID character varying(48) 
, PART double precision 
, CONSTRAINT LAG_PARTY_MEMBER_PK PRIMARY KEY 
  (
    GROUP_ID 
  , PARTY_ID 
  )
);

ALTER TABLE GCM.LAG_PARTY_MEMBER OWNER TO GCM;

CREATE TABLE GCM.LAG_AREA_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_AREA_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_AREA_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_DIMENSION_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_DIMENSION_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_DIMENSION_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_LEVEL_CONTENT_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_LEVEL_CONTENT_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_LEVEL_CONTENT_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_REGISTER_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_REGISTER_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_REGISTER_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_STRUCTURE_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_STRUCTURE_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_STRUCTURE_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_SURFACE_RELATION_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_SURFACE_RELATION_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_SURFACE_RELATION_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_VOLUME_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(80) 
, CONSTRAINT LAG_VOLUME_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.LAG_VOLUME_TYPE OWNER TO GCM;

CREATE TABLE GCM.LAG_LEVEL 
(
  OID character varying(48) NOT NULL 
, NAME character varying(255) 
, REGISTER_TYPE character varying(3) 
, STRUCTURE character varying(3) 
, TYPE character varying(3) 
, CONSTRAINT LAG_LEVEL_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_LEVEL OWNER TO GCM;

CREATE TABLE GCM.LAG_SPATIAL_UNIT 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, LEVEL_ID character varying(48) 
, AREA double precision 
, AREA_TYPE character varying(3) 
, DIMENSION_TYPE character varying(3) 
, ADDRESS_ID character varying(48) 
, LABEL character varying(255) NOT NULL 
, SURFACE_RELATION character varying(3) 
, VOLUME double precision 
, VOLUME_TYPE character varying(3) 
, LAND_USE character varying(3) 
, CONSTRAINT LAG_SPATIAL_UNIT_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT OWNER TO GCM;

CREATE INDEX LAG_SUNIT_LOCAL_ID_IX ON GCM.LAG_SPATIAL_UNIT (LOCAL_ID);

CREATE TABLE GCM.EXT_ADM_USE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(255) 
, CONSTRAINT EXT_ADM_USE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_ADM_USE OWNER TO GCM;

CREATE TABLE GCM.EXT_COUNTRY 
(
  CODE character varying(2) NOT NULL 
, NAME character varying(255) 
, CONSTRAINT EXT_COUNTRIES_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_COUNTRY OWNER TO GCM;

CREATE TABLE GCM.EXT_LAND_USE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(255) 
, CONSTRAINT EXT_LAND_USE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_LAND_USE OWNER TO GCM;

CREATE TABLE GCM.EXT_MUNICIPALITY 
(
  CODE character varying(16) NOT NULL 
, LOCAL_ID character varying(20) 
, NAME character varying(255) 
, CONSTRAINT EXT_MUNICIPALITY_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_MUNICIPALITY OWNER TO GCM;

CREATE TABLE GCM.EXT_STATE_PROVINCE 
(
  CODE character varying(8) NOT NULL 
, LOCAL_ID character varying(20) 
, NAME character varying(255) 
, CONSTRAINT EXT_STATE_PROVINCE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_STATE_PROVINCE OWNER TO GCM;

CREATE TABLE GCM.EXT_TAX_TYPE 
(
  CODE character varying(8) NOT NULL 
, DESCRIPTION character varying(255) 
, CONSTRAINT EXT_TAX_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_TAX_TYPE OWNER TO GCM;

CREATE TABLE GCM.EXT_VALUATION_TYPE 
(
  CODE character varying(3) NOT NULL 
, DESCRIPTION character varying(255) 
, CONSTRAINT EXT_VALUATION_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
);

ALTER TABLE GCM.EXT_VALUATION_TYPE OWNER TO GCM;

CREATE TABLE GCM.EXT_ADDRESS 
(
  OID character varying(48) NOT NULL 
, ADDRESS_ID character varying(32) 
, STREET_NAME character varying(255) 
, BUILDING_NAME character varying(255) 
, BUILDING_NUMBER character varying(12) 
, POSTAL_CODE character varying(12) 
, POST_BOX character varying(12) 
, MUNICIPALITY character varying(16) 
, STATE_PROVINCE character varying(8) 
, COUNTRY character varying(2) 
, CONSTRAINT EXT_ADDRESS_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.EXT_ADDRESS OWNER TO GCM;

CREATE INDEX EXT_ADDRESS_LOCAL_ID_IX ON GCM.EXT_ADDRESS (ADDRESS_ID);

CREATE TABLE GCM.EXT_TAXATION 
(
  OID character varying(48) NOT NULL 
, LOCAL_ID character varying(48) 
, BA_UNIT_ID character varying(48) 
, PARTY_ID character varying(48) 
, FISCAL_PERIOD character varying(12) 
, TAX_TYPE character varying(3) 
, TAX_DATE timestamp without time zone
, AMOUNT double precision 
, AMOUNT_PAID double precision 
, CONSTRAINT EXT_TAXATION_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.EXT_TAXATION OWNER TO GCM;

CREATE INDEX EXT_TAXATION_LOCAL_ID_IX ON GCM.EXT_TAXATION (LOCAL_ID);

CREATE TABLE GCM.EXT_VALUATION 
(
  OID character varying(48) NOT NULL 
, BA_UNIT_ID character varying(48) 
, PERIOD smallint
, VALUE double precision 
, VALUE_DATE timestamp without time zone
, VALUE_TYPE character varying(3) 
, CONSTRAINT EXT_VALUATION_PK PRIMARY KEY 
  (
    OID 
  )
);

ALTER TABLE GCM.EXT_VALUATION OWNER TO GCM;

CREATE UNIQUE INDEX EXT_VALUATION_AK ON GCM.EXT_VALUATION (BA_UNIT_ID, PERIOD);

-------------------------------------------------------------------------------------------------------
-- CREACIÓN DE RELACIONES DE CLAVES FORÁNEAS
-------------------------------------------------------------------------------------------------------
ALTER TABLE GCM.LAG_ADM_SOURCE
ADD CONSTRAINT LAG_ASOURCE_ASTATUSTYPE_FK FOREIGN KEY
(
  AVAIL_STATUS 
)
REFERENCES GCM.LAG_AVAIL_STATUS_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_ADM_SOURCE
ADD CONSTRAINT LAG_ASOURCE_PFORMCODE_FK FOREIGN KEY
(
  MAIN_TYPE 
)
REFERENCES GCM.CI_PRES_FORM_CODE
(
  CODE 
);

ALTER TABLE GCM.LAG_ADM_SOURCE
ADD CONSTRAINT LAG_ASOURCE_RESPONSABLE_FK FOREIGN KEY
(
  SOURCE 
)
REFERENCES GCM.CI_RESPONSABLE_PARTY
(
  OID 
);

ALTER TABLE GCM.LAG_BA_UNIT
ADD CONSTRAINT LAG_BA_UNIT_ADM_USE_FK FOREIGN KEY
(
  ADM_USE 
)
REFERENCES GCM.EXT_ADM_USE
(
  CODE 
);

ALTER TABLE GCM.LAG_BA_UNIT
ADD CONSTRAINT LAG_BA_UNIT_SUNIT_FK FOREIGN KEY
(
  SUNIT_ID 
)
REFERENCES GCM.LAG_SPATIAL_UNIT
(
  OID 
);

ALTER TABLE GCM.LAG_BA_UNIT
ADD CONSTRAINT LAG_BA_UNIT_TYPE_FK FOREIGN KEY
(
  BA_UNIT_TYPE 
)
REFERENCES GCM.LAG_BA_UNIT_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LAG_RIGHT_ASOURCE_FK FOREIGN KEY
(
  SOURCE_ID 
)
REFERENCES GCM.LAG_ADM_SOURCE
(
  OID 
);

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LA_RIGHT_BA_UNIT_FK FOREIGN KEY
(
  BAUNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
);

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LA_RIGHT_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
);

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LA_RIGHT_TYPE_FK FOREIGN KEY
(
  RIGHT_TYPE 
)
REFERENCES GCM.LAG_RIGHT_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_CROPS
ADD CONSTRAINT LA_CROPS_BA_UNIT_FK FOREIGN KEY
(
  BAUNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
);

ALTER TABLE GCM.LAG_CROPS
ADD CONSTRAINT LA_CROPS_TYPE_FK FOREIGN KEY
(
  CROP_TYPE 
)
REFERENCES GCM.LAG_CROPS_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_GROUP_PARTY
ADD CONSTRAINT LAG_GROUP_PARTY_PARTY_FK FOREIGN KEY
(
  OID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
);

ALTER TABLE GCM.LAG_PARTY
ADD CONSTRAINT LAG_PARTY_ADDRESS_FK FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES GCM.EXT_ADDRESS
(
  OID 
);

ALTER TABLE GCM.LAG_PARTY
ADD CONSTRAINT LAG_PARTY_ROLE_FK FOREIGN KEY
(
  PARTY_ROLE 
)
REFERENCES GCM.LAG_PARTY_ROLE_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_PARTY
ADD CONSTRAINT LAG_PARTY_TYPE_FK FOREIGN KEY
(
  PARTY_TYPE 
)
REFERENCES GCM.LAG_PARTY_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_PARTY_MEMBER
ADD CONSTRAINT LAG_PARTY_MEMBER_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES GCM.LAG_GROUP_PARTY
(
  OID 
)
ON DELETE CASCADE;

ALTER TABLE GCM.LAG_PARTY_MEMBER
ADD CONSTRAINT LAG_PARTY_MEMBER_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
)
ON DELETE CASCADE;

ALTER TABLE GCM.LAG_LEVEL
ADD CONSTRAINT LAG_LEVEL_CONTENT_FK FOREIGN KEY
(
  TYPE 
)
REFERENCES GCM.LAG_LEVEL_CONTENT_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_LEVEL
ADD CONSTRAINT LAG_LEVEL_REGISTER_FK FOREIGN KEY
(
  REGISTER_TYPE 
)
REFERENCES GCM.LAG_REGISTER_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_LEVEL
ADD CONSTRAINT LAG_LEVEL_STRUCTURE_FK FOREIGN KEY
(
  STRUCTURE 
)
REFERENCES GCM.LAG_STRUCTURE_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_ADDRESS_FK FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES GCM.EXT_ADDRESS
(
  OID 
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_AREA_FK FOREIGN KEY
(
  AREA_TYPE 
)
REFERENCES GCM.LAG_AREA_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_DIMENSION_FK FOREIGN KEY
(
  DIMENSION_TYPE 
)
REFERENCES GCM.LAG_DIMENSION_TYPE
(
  CODE 
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_LAND_USE_FK FOREIGN KEY
(
  LAND_USE 
)
REFERENCES GCM.EXT_LAND_USE
(
  CODE 
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_LEVEL_FK FOREIGN KEY
(
  LEVEL_ID 
)
REFERENCES GCM.LAG_LEVEL
(
  OID 
);

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_VOLUME_FK FOREIGN KEY
(
  VOLUME_TYPE 
)
REFERENCES GCM.LAG_VOLUME_TYPE
(
  CODE 
);

ALTER TABLE GCM.EXT_ADDRESS
ADD CONSTRAINT EXT_ADDRESS_COUNTRY_FK FOREIGN KEY
(
  COUNTRY 
)
REFERENCES GCM.EXT_COUNTRY
(
  CODE 
);

ALTER TABLE GCM.EXT_ADDRESS
ADD CONSTRAINT EXT_ADDRESS_MUNICIPALITY_FK FOREIGN KEY
(
  MUNICIPALITY 
)
REFERENCES GCM.EXT_MUNICIPALITY
(
  CODE 
);

ALTER TABLE GCM.EXT_ADDRESS
ADD CONSTRAINT EXT_ADDRESS_STATE_PROVINCE_FK FOREIGN KEY
(
  STATE_PROVINCE 
)
REFERENCES GCM.EXT_STATE_PROVINCE
(
  CODE 
);

ALTER TABLE GCM.EXT_TAXATION
ADD CONSTRAINT EXT_TAXATION_BA_UNIT_FK FOREIGN KEY
(
  BA_UNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
);

ALTER TABLE GCM.EXT_TAXATION
ADD CONSTRAINT EXT_TAXATION_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
);

ALTER TABLE GCM.EXT_TAXATION
ADD CONSTRAINT EXT_TAXATION_TAX_TYPE_FK FOREIGN KEY
(
  TAX_TYPE 
)
REFERENCES GCM.EXT_TAX_TYPE
(
  CODE 
);

ALTER TABLE GCM.EXT_VALUATION
ADD CONSTRAINT EXT_VALUATION_BA_UNIT_FK FOREIGN KEY
(
  BA_UNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
);

ALTER TABLE GCM.EXT_VALUATION
ADD CONSTRAINT EXT_VALUATION_VAL_TYPE_FK FOREIGN KEY
(
  VALUE_TYPE 
)
REFERENCES GCM.EXT_VALUATION_TYPE
(
  CODE 
);

--------------------------------------------------------------------------------------------------------
-- CÓDIGO PLSQL Y VISTAS DE DATOS
--------------------------------------------------------------------------------------------------------
CREATE FUNCTION GCM.ReturnOID() RETURNS trigger AS
$BODY$
BEGIN
   IF NEW.OID IS NULL THEN
      NEW.OID := uuid_generate_v4();
   END IF;

   RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;

ALTER FUNCTION GCM.ReturnOID() OWNER TO GCM;

CREATE TRIGGER tr_ci_responsable_party
BEFORE INSERT ON GCM.ci_responsable_party 
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_ext_address
BEFORE INSERT ON GCM.ext_address
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_ext_taxation
BEFORE INSERT ON GCM.ext_taxation
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_ext_valuation
BEFORE INSERT ON GCM.ext_valuation
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_adm_source
BEFORE INSERT ON GCM.lag_adm_source
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_ba_unit
BEFORE INSERT ON GCM.lag_ba_unit
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_group_party
BEFORE INSERT ON GCM.lag_group_party
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_level
BEFORE INSERT ON GCM.lag_level
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_party
BEFORE INSERT ON GCM.lag_party
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_right
BEFORE INSERT ON GCM.lag_right
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_crops
BEFORE INSERT ON GCM.lag_crops
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

CREATE TRIGGER tr_lag_spatial_unit
BEFORE INSERT ON GCM.lag_spatial_unit
FOR EACH ROW EXECUTE PROCEDURE GCM.ReturnOID();

----------------------------------------------------------
-- VISTA DE VALORES CATASTRALES DE LAS UNIDADES BÁSICAS --
----------------------------------------------------------
CREATE OR REPLACE VIEW GCM.VW_EXT_CUR_VALUATION AS
SELECT BU.OID, BU.LOCAL_ID, EV.PERIOD, EV.VALUE, EV.VALUE_DATE, 
       EV.VALUE_TYPE, EVT.DESCRIPTION AS VALUE_TYPE_DESC
FROM
 (SELECT BA_UNIT_ID, MAX(PERIOD) AS LAST_PERIOD
  FROM GCM.EXT_VALUATION GROUP BY BA_UNIT_ID) LAST_VAL
INNER JOIN GCM.LAG_BA_UNIT BU ON (BU.OID=LAST_VAL.BA_UNIT_ID)
INNER JOIN GCM.EXT_VALUATION EV ON (EV.BA_UNIT_ID=LAST_VAL.BA_UNIT_ID AND EV.PERIOD=LAST_VAL.LAST_PERIOD)
LEFT OUTER JOIN GCM.EXT_VALUATION_TYPE EVT ON (EVT.CODE=EV.VALUE_TYPE); 

ALTER TABLE GCM.vw_ext_cur_valuation OWNER TO GCM;

------------------------
-- VISTA DE IMPUESTOS --
------------------------
CREATE OR REPLACE VIEW GCM.VW_EXT_CUR_TAXATION AS
SELECT BU.OID, BU.LOCAL_ID, ET.FISCAL_PERIOD, ET.TAX_TYPE, ETT.DESCRIPTION AS TAX_TYPE_DESC, ET.TAX_DATE,
       ET.AMOUNT, ET.AMOUNT_PAID, 
       CASE WHEN ET.AMOUNT=0 THEN 0 ELSE ROUND(CAST((ET.AMOUNT_PAID / ET.AMOUNT) * 100 AS NUMERIC), 2) END  AS PERCENT_PAID
FROM
 (SELECT BA_UNIT_ID, MAX(FISCAL_PERIOD) AS LAST_PERIOD
  FROM GCM.EXT_TAXATION GROUP BY BA_UNIT_ID) LAST_TAX
INNER JOIN GCM.LAG_BA_UNIT BU ON (BU.OID=LAST_TAX.BA_UNIT_ID)
INNER JOIN GCM.EXT_TAXATION ET ON (ET.BA_UNIT_ID=LAST_TAX.BA_UNIT_ID AND ET.FISCAL_PERIOD=LAST_TAX.LAST_PERIOD)
LEFT OUTER JOIN GCM.EXT_TAX_TYPE ETT ON (ETT.CODE=ET.TAX_TYPE); 

ALTER TABLE GCM.vw_ext_cur_taxation OWNER TO GCM;

---------------------------------------------------
-- VISTA DE LAS UNIDADES BÁSICAS ADMINISTRATIVAS --
---------------------------------------------------
CREATE OR REPLACE VIEW GCM.VW_BA_UNIT AS
SELECT B.OID, B.LOCAL_ID, B.BA_UNIT_TYPE, BUT.DESCRIPTION AS BA_UNIT_TYPE_DESCRIP,
       B.PLACE_NAME, SU.LOCAL_ID AS SUNIT_LOCAL_ID, SU.AREA, SU.AREA_TYPE, 
       LAT.DESCRIPTION AS AREA_TYPE_DESCRIP, SU.DIMENSION_TYPE, LDT.DESCRIPTION AS DIMENSION_TYPE_DESCRIP, 
       SU.LABEL AS SPATIAL_UNIT_DESCRIP, SU.LAND_USE, ELU.DESCRIPTION AS LAND_USE_DESCRIP, B.ADM_USE, 
       EAU.DESCRIPTION AS ADM_USE_DESCRIP, EV.VALUE, EV.VALUE_DATE, EV.VALUE_TYPE, EV.VALUE_TYPE_DESC,
       EA.ADDRESS_ID, EA.STREET_NAME, EA.BUILDING_NAME, EA.BUILDING_NUMBER, EA.POSTAL_CODE, EA.POST_BOX, 
       EM.LOCAL_ID AS MUN_CODE, EM.NAME MUN_NAME, ESP.LOCAL_ID AS SP_CODE, ESP.NAME AS SP_NAME,
       EC.CODE AS COUNTRY_CODE, EC.NAME AS COUNTRY_NAME   
FROM GCM.LAG_BA_UNIT B
LEFT OUTER JOIN GCM.LAG_BA_UNIT_TYPE BUT ON (BUT.CODE=B.BA_UNIT_TYPE)
LEFT OUTER JOIN GCM.EXT_ADM_USE EAU ON (EAU.CODE=B.ADM_USE)
LEFT OUTER JOIN GCM.VW_EXT_CUR_VALUATION EV ON (EV.OID=B.OID)
LEFT OUTER JOIN GCM.LAG_SPATIAL_UNIT SU ON (SU.OID=B.SUNIT_ID)
LEFT OUTER JOIN GCM.LAG_AREA_TYPE LAT ON (LAT.CODE=SU.AREA_TYPE)
LEFT OUTER JOIN GCM.LAG_DIMENSION_TYPE LDT ON (LDT.CODE=SU.DIMENSION_TYPE)
LEFT OUTER JOIN GCM.EXT_LAND_USE ELU ON (ELU.CODE=SU.LAND_USE)
LEFT OUTER JOIN GCM.EXT_ADDRESS EA ON (EA.OID=SU.ADDRESS_ID)
LEFT OUTER JOIN GCM.EXT_MUNICIPALITY EM ON (EM.CODE=EA.MUNICIPALITY)
LEFT OUTER JOIN GCM.EXT_STATE_PROVINCE ESP ON (ESP.CODE=EA.STATE_PROVINCE)
LEFT OUTER JOIN GCM.EXT_COUNTRY EC ON (EC.CODE=EA.COUNTRY);

ALTER TABLE GCM.vw_ba_unit OWNER TO GCM;

-----------------------------------------------------------
-- VISTA DE DERECHOS DE PROPIEDAD SOBRE UNIDADES BÁSICAS --
-----------------------------------------------------------
CREATE OR REPLACE VIEW GCM.VW_RIGHT AS
SELECT R.OID, R.LOCAL_ID, R.RIGHT_TYPE, RT.DESCRIPTION RIGHT_TYPE_DESC, R.SHARES, P.LOCAL_ID PARTY_LOCAL_ID, 
       P.NAME PARTY_NAME, P.PARTY_ROLE, PT.DESCRIPTION PARTY_ROLE_DESC, EA.ADDRESS_ID PARTY_ADDRESS_ID, 
       EA.STREET_NAME PARTY_STREET_NAME, EA.BUILDING_NAME PARTY_BUILDING_NAME, EA.BUILDING_NUMBER PARTY_BUILDING_NUMBER, 
       EA.POSTAL_CODE PARTY_POSTAL_CODE, EA.POST_BOX PARTY_POST_BOX, EM.LOCAL_ID PARTY_MUN_CODE, EM.NAME PARTY_MUN_NAME, 
       ESP.LOCAL_ID PARTY_SP_CODE, ESP.NAME PARTY_SP_NAME, EC.CODE PARTY_COUNTRY_CODE, EC.NAME PARTY_COUNTRY_NAME
FROM GCM.LAG_RIGHT R
LEFT OUTER JOIN GCM.LAG_RIGHT_TYPE RT ON (RT.CODE=R.RIGHT_TYPE)
LEFT OUTER JOIN GCM.LAG_PARTY P ON (P.OID=R.PARTY_ID)
LEFT OUTER JOIN GCM.LAG_PARTY_ROLE_TYPE PT ON (PT.CODE=P.PARTY_ROLE)
LEFT OUTER JOIN GCM.EXT_ADDRESS EA ON (EA.OID=P.ADDRESS_ID)
LEFT OUTER JOIN GCM.EXT_MUNICIPALITY EM ON (EM.CODE=EA.MUNICIPALITY)
LEFT OUTER JOIN GCM.EXT_STATE_PROVINCE ESP ON (ESP.CODE=EA.STATE_PROVINCE)
LEFT OUTER JOIN GCM.EXT_COUNTRY EC ON (EC.CODE=EA.COUNTRY);

ALTER TABLE GCM.vw_right OWNER TO GCM;

------------------------
-- VISTA DE CULTIVOS  --
------------------------
CREATE OR REPLACE VIEW GCM.VW_CROPS
AS
SELECT CU.OID, CU.LOCAL_ID, CU.CROP_TYPE, COALESCE(TC.DESCRIPTION, 'CULTIVO ' || CU.CROP_TYPE) AS CROP_TYPE_DESC, CU.AREA, CU.ECONOMIC_VALUE   
FROM GCM.LAG_CROPS CU
LEFT OUTER JOIN GCM.LAG_CROPS_TYPE TC ON (TC.CODE=CU.CROP_TYPE);

ALTER TABLE GCM.VW_CROPS OWNER TO GCM;

--------------------------------------------------------------------------------------------------------
-- COMENTARIOS DE COLUMNAS
--------------------------------------------------------------------------------------------------------
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.OID IS 'Codigo Unico Global';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.INDIVIDUAL_NAME IS 'Nombre del Responsable';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.ORGANIZATION_NAME IS 'Nombre de la Organizacion responsable';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.POSITION_NAME IS 'Cargo de la Persona responsable';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.ADDRESS IS 'Direccion de contacto';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.EMAIL IS 'Correo Electronico';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.PHONE_NUMBER IS 'Numero de Telefono de contacto';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.FAX_NUMBER IS 'Numero de Fax de contacto';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.ROLE IS 'Funcion realizada por la parte responsable';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.DESCRIPTION IS 'Descripcion del Documento';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.SOURCE_TYPE IS 'Tipo de Documento de fuente administrativa';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.TRANSACTION_CODE IS 'Codigo Registral/Documental de la transaccion';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.ACCEPTANCE IS 'Fecha de Vigencia de la Ley de la fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.AVAIL_STATUS IS 'Estado de Disponibilidad';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.EXT_ARCHIVE_ID IS 'Identificador de la fuente en un registro externo';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.LIFE_SPAN_STAMP IS 'Fecha de inicio de validez de la fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.MAIN_TYPE IS 'Tipo de Documento';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.QUALITY IS 'Calidad de la Fuente (DQ_Element ISO 19115)';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.RECORDATION IS 'Fecha de Registro de la fuente por la Autoridad';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.SOURCE IS 'Responsable de la Fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.SUBMISSION IS 'Fecha de Presentacion de la Fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.OFFICIAL IS 'Si es un documento oficial';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_AVAIL_STATUS_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_AVAIL_STATUS_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.OID IS 'Identificador Único Global';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.BA_UNIT_TYPE IS 'Tipo';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.PLACE_NAME IS 'Nombre Toponimico';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.SUNIT_ID IS 'Identificador de Unidad Espacial';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.ADM_USE IS 'Uso Economico/Administrativo de la Unidad';
COMMENT ON COLUMN GCM.LAG_BA_UNIT_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_BA_UNIT_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.CI_PRES_FORM_CODE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.CI_PRES_FORM_CODE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_RIGHT.OID IS 'Identificador Único Global';
COMMENT ON COLUMN GCM.LAG_RIGHT.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_RIGHT.BAUNIT_ID IS 'Identificador de la Unidad Administrativa';
COMMENT ON COLUMN GCM.LAG_RIGHT.PARTY_ID IS 'Identificador del Interesado';
COMMENT ON COLUMN GCM.LAG_RIGHT.SOURCE_ID IS 'Identificador de la fuente administrativa del Derecho';
COMMENT ON COLUMN GCM.LAG_RIGHT.DESCRIPCION IS 'Descripcion del Derecho';
COMMENT ON COLUMN GCM.LAG_RIGHT.RIGHT_TYPE IS 'Tipo de Derecho';
COMMENT ON COLUMN GCM.LAG_RIGHT.SHARES IS 'Cuota de Participacion';
COMMENT ON COLUMN GCM.LAG_RIGHT.SHARE_CHECK IS 'Indicada si la participacion es compartida';
COMMENT ON COLUMN GCM.LAG_RIGHT.TIME_SPEC IS 'Periodo de vigencia (si existe) del derecho (ISO 8601).';
COMMENT ON COLUMN GCM.LAG_RIGHT_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_RIGHT_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_CROPS.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_CROPS.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_CROPS.BAUNIT_ID IS 'Identificador de la BAUnit matriz del Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.CROP_TYPE IS 'Tipo de Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.AREA IS 'Superficie del Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.ECONOMIC_VALUE IS 'Valor Economico del Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_CROPS_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_GROUP_PARTY.OID IS 'Identificador del Grupo de Interesados';
COMMENT ON COLUMN GCM.LAG_GROUP_PARTY.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_GROUP_PARTY.GROUP_PARTY_TYPE IS 'Tipo de Grupo de Interesados';
COMMENT ON COLUMN GCM.LAG_PARTY.OID IS 'Identificador unico de interesado';
COMMENT ON COLUMN GCM.LAG_PARTY.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_PARTY.NAME IS 'Nombre del Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY.PARTY_ROLE IS 'Rol de interesado en el proceso de actualizacion y mantenimiento';
COMMENT ON COLUMN GCM.LAG_PARTY.PARTY_TYPE IS 'Tipo de Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY.ADDRESS_ID IS 'Identificador de Direccion Postal';
COMMENT ON COLUMN GCM.LAG_PARTY_MEMBER.GROUP_ID IS 'Identificador del Grupo de Interesados';
COMMENT ON COLUMN GCM.LAG_PARTY_MEMBER.PARTY_ID IS 'Identificador del Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY_MEMBER.PART IS 'Porcentaje de Participacion (0..1)';
COMMENT ON COLUMN GCM.LAG_PARTY_ROLE_TYPE.CODE IS 'Codigo de Rol';
COMMENT ON COLUMN GCM.LAG_PARTY_ROLE_TYPE.DESCRIPTION IS 'Descripcion del Rol';
COMMENT ON COLUMN GCM.LAG_PARTY_TYPE.CODE IS 'Codigo de Tipo de Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY_TYPE.DESCRIPTION IS 'Descripcion del Tipo de Interesado';
COMMENT ON COLUMN GCM.LAG_AREA_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_AREA_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_DIMENSION_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_DIMENSION_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_LEVEL.OID IS 'Identificador unico de interesado';
COMMENT ON COLUMN GCM.LAG_LEVEL.NAME IS 'Nombre del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL.REGISTER_TYPE IS 'Tipo de Registro del contenido del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL.STRUCTURE IS 'Estructura de la geometria del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL.TYPE IS 'Tipo de contenido del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL_CONTENT_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_LEVEL_CONTENT_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_REGISTER_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_REGISTER_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LEVEL_ID IS 'Identificador de Nivel';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.AREA IS 'Area de la Unidad Espacial';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.AREA_TYPE IS 'Tipo de Área';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.DIMENSION_TYPE IS 'Dimension del Area';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.ADDRESS_ID IS 'Identificador de Direccion Postal';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LABEL IS 'Descripcion textual de la Undad Espacial';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.SURFACE_RELATION IS 'Indica cuando la unidad espacial esta por encima o por debajo de la superficie.';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.VOLUME IS 'Volumen de la Unidad Espacial en m3';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.VOLUME_TYPE IS 'Tipo de Volumen';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LAND_USE IS 'Tipo de Uso del Suelo';
COMMENT ON COLUMN GCM.LAG_STRUCTURE_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_STRUCTURE_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_SURFACE_RELATION_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_SURFACE_RELATION_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_VOLUME_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_VOLUME_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.EXT_ADDRESS.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.EXT_ADDRESS.ADDRESS_ID IS 'Identificador de la Direccion Postal Externa';
COMMENT ON COLUMN GCM.EXT_ADDRESS.STREET_NAME IS 'Nombre de la Calle';
COMMENT ON COLUMN GCM.EXT_ADDRESS.BUILDING_NAME IS 'Nombre del Edificio';
COMMENT ON COLUMN GCM.EXT_ADDRESS.BUILDING_NUMBER IS 'Numero del Edificio';
COMMENT ON COLUMN GCM.EXT_ADDRESS.POSTAL_CODE IS 'Codigo Postal';
COMMENT ON COLUMN GCM.EXT_ADDRESS.POST_BOX IS 'Apartado de Correos';
COMMENT ON COLUMN GCM.EXT_ADDRESS.MUNICIPALITY IS 'Codigo de Municipio/Ciudad';
COMMENT ON COLUMN GCM.EXT_ADDRESS.STATE_PROVINCE IS 'Codigo de Estado/Departamento/Provincia';
COMMENT ON COLUMN GCM.EXT_ADDRESS.COUNTRY IS 'Codigo de País';
COMMENT ON COLUMN GCM.EXT_ADM_USE.CODE IS 'Codigo de Uso';
COMMENT ON COLUMN GCM.EXT_ADM_USE.DESCRIPTION IS 'Descripcion del Uso';
COMMENT ON COLUMN GCM.EXT_COUNTRY.CODE IS 'Codigo de Pais según ISO 3166-1';
COMMENT ON COLUMN GCM.EXT_COUNTRY.NAME IS 'Nombre del Pais';
COMMENT ON COLUMN GCM.EXT_LAND_USE.CODE IS 'Codigo de Tipo de Uso del Suelo';
COMMENT ON COLUMN GCM.EXT_LAND_USE.DESCRIPTION IS 'Descripcion del tipo de Uso del Suelo';
COMMENT ON COLUMN GCM.EXT_MUNICIPALITY.CODE IS 'Codigo de Municipio';
COMMENT ON COLUMN GCM.EXT_MUNICIPALITY.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.EXT_MUNICIPALITY.NAME IS 'Nombre del Municipio';
COMMENT ON COLUMN GCM.EXT_STATE_PROVINCE.CODE IS 'Codigo de Estado/Departamento/Provincia según ISO 3166-2';
COMMENT ON COLUMN GCM.EXT_STATE_PROVINCE.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.EXT_STATE_PROVINCE.NAME IS 'Nombre del Estado/Departamento/Provincia';
COMMENT ON COLUMN GCM.EXT_TAXATION.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.EXT_TAXATION.LOCAL_ID IS 'Referencia Local del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.BA_UNIT_ID IS 'Identificador de la BAUnit asociada al Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.PARTY_ID IS 'Identificador del Interesado';
COMMENT ON COLUMN GCM.EXT_TAXATION.FISCAL_PERIOD IS 'Ejercicio Fiscal';
COMMENT ON COLUMN GCM.EXT_TAXATION.TAX_TYPE IS 'Tipo del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.TAX_DATE IS 'Fecha del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.AMOUNT IS 'Importe del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.AMOUNT_PAID IS 'Cantidad Pagada';
COMMENT ON COLUMN GCM.EXT_TAX_TYPE.CODE IS 'Codigo de Tipo de Impuesto/Tasa';
COMMENT ON COLUMN GCM.EXT_TAX_TYPE.DESCRIPTION IS 'Descripcion del Impuesto/Tasa';
COMMENT ON COLUMN GCM.EXT_VALUATION.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.EXT_VALUATION.BA_UNIT_ID IS 'Identificador de Unidad Administrativa valorada';
COMMENT ON COLUMN GCM.EXT_VALUATION.PERIOD IS 'Periodo en el que rige la valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION.VALUE IS 'Valoracion de la Undiad Administrativa';
COMMENT ON COLUMN GCM.EXT_VALUATION.VALUE_DATE IS 'Fecha de la Valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION.VALUE_TYPE IS 'Tipo de Valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION_TYPE.CODE IS 'Codigo de Tipo de Valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION_TYPE.DESCRIPTION IS 'Descripcion del Tipo de Valoracion';
