-----------------------------------------------------------------
-- CREACIÓN DEL USUARIO GCM
-----------------------------------------------------------------
CREATE USER GCM IDENTIFIED BY GCM PROFILE DEFAULT ACCOUNT UNLOCK;

GRANT CONNECT TO GCM;

ALTER USER GCM DEFAULT ROLE ALL;

GRANT UNLIMITED TABLESPACE TO GCM;
GRANT CREATE SESSION TO GCM;

GRANT CREATE TABLE TO GCM;
GRANT CREATE PROCEDURE TO GCM;
GRANT CREATE TRIGGER TO GCM;
GRANT CREATE VIEW TO GCM;

GRANT CREATE SESSION TO GCM;

GRANT EXPORT FULL DATABASE TO GCM;
GRANT IMPORT FULL DATABASE TO GCM;

-- MODIFICAR SEGÚN EL NOMBRE DEL TABLESPACE DE USUARIO
--ALTER USER GCM QUOTA UNLIMITED ON <usr_tablespace>;
ALTER USER GCM QUOTA UNLIMITED ON USR;

-----------------------------------------------------------------
-- CREACIÓN DE TABLAS, CLAVES PRIMARIAS E ÍNDICES
-----------------------------------------------------------------
CREATE TABLE GCM.CI_RESPONSABLE_PARTY 
(
  OID VARCHAR2(48) NOT NULL 
, INDIVIDUAL_NAME VARCHAR2(255) 
, ORGANIZATION_NAME VARCHAR2(255) 
, POSITION_NAME VARCHAR2(255) 
, ADDRESS VARCHAR2(255) 
, EMAIL VARCHAR2(255) 
, PHONE_NUMBER VARCHAR2(32) 
, FAX_NUMBER VARCHAR2(32) 
, ROLE VARCHAR2(255) 
, CONSTRAINT CI_RESPONSABLE_PARTY_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_ADM_SOURCE_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_ADM_SOURCE_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_AVAIL_STATUS_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LA_AVAIL_STATUS_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_BA_UNIT_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_BA_UNIT_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.CI_PRES_FORM_CODE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT CI_PRES_FORM_CODE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_RIGHT_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_RIGHT_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_BA_UNIT 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, BA_UNIT_TYPE VARCHAR2(3) 
, PLACE_NAME VARCHAR2(80) 
, SUNIT_ID VARCHAR2(48) 
, ADM_USE VARCHAR2(3) 
, CONSTRAINT LAG_BA_UNIT_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.LAG_BA_UNIT_LOCAL_ID_IX ON GCM.LAG_BA_UNIT
(LOCAL_ID)
NOLOGGING
PCTFREE    5
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE GCM.LAG_ADM_SOURCE 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, DESCRIPTION VARCHAR2(255) 
, SOURCE_TYPE VARCHAR2(3) 
, TRANSACTION_CODE VARCHAR2(80) 
, ACCEPTANCE DATE 
, AVAIL_STATUS VARCHAR2(3) 
, EXT_ARCHIVE_ID VARCHAR2(48) 
, LIFE_SPAN_STAMP DATE 
, MAIN_TYPE VARCHAR2(3) 
, QUALITY VARCHAR2(48) 
, RECORDATION DATE 
, SOURCE VARCHAR2(48) 
, SUBMISSION DATE 
, OFFICIAL NUMBER(1) DEFAULT 1 
, DOCUMENT BLOB 
, CONSTRAINT LAG_ADM_SOURCE_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.LAG_ADM_SOURCE_LOCAL_ID_IX ON GCM.LAG_ADM_SOURCE
(LOCAL_ID)
NOLOGGING
PCTFREE    5
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE GCM.LAG_RIGHT 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, BAUNIT_ID VARCHAR2(48) 
, PARTY_ID VARCHAR2(48) 
, SOURCE_ID VARCHAR2(48) 
, DESCRIPCION VARCHAR2(255) 
, RIGHT_TYPE VARCHAR2(3) 
, SHARES NUMBER 
, SHARE_CHECK NUMBER(1) DEFAULT 0 
, TIME_SPEC VARCHAR2(64) 
, CONSTRAINT LAG_RIGHT_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.LAG_RIGHT_LOCAL_ID_IX ON GCM.LAG_RIGHT
(LOCAL_ID)
NOLOGGING
PCTFREE    5
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE GCM.LAG_CROPS
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, BAUNIT_ID VARCHAR2(48) 
, CROP_TYPE VARCHAR2(3) 
, AREA NUMBER 
, ECONOMIC_VALUE NUMBER 
, POLYGON MDSYS.SDO_GEOMETRY
, CONSTRAINT LAG_CROPS_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.LAG_CROPS_LOCAL_ID_IX ON GCM.LAG_CROPS
(LOCAL_ID)
NOLOGGING
PCTFREE    5
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE GCM.LAG_CROPS_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_CROPS_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_PARTY_ROLE_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_PARTY_ROLE_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_PARTY_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_PARTY_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_PARTY 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, NAME VARCHAR2(255) 
, PARTY_ROLE VARCHAR2(3) 
, PARTY_TYPE VARCHAR2(3) 
, ADDRESS_ID VARCHAR2(48) 
, CONSTRAINT LAG_PARTY_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.LAG_PARTY_LOCAL_ID_IX ON GCM.LAG_PARTY
(LOCAL_ID)
NOLOGGING
PCTFREE    5
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE GCM.LAG_GROUP_PARTY 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, GROUP_PARTY_TYPE VARCHAR2(3) 
, CONSTRAINT LAG_GROUP_PARTY_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_PARTY_MEMBER 
(
  GROUP_ID VARCHAR2(48) NOT NULL 
, PARTY_ID VARCHAR2(48) 
, PART NUMBER 
, CONSTRAINT LAG_PARTY_MEMBER_PK PRIMARY KEY 
  (
    GROUP_ID 
  , PARTY_ID 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_AREA_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_AREA_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_DIMENSION_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_DIMENSION_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_LEVEL_CONTENT_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_LEVEL_CONTENT_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_REGISTER_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_REGISTER_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_STRUCTURE_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_STRUCTURE_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_SURFACE_RELATION_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_SURFACE_RELATION_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_VOLUME_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(80) 
, CONSTRAINT LAG_VOLUME_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_LEVEL 
(
  OID VARCHAR2(48) NOT NULL 
, NAME VARCHAR2(255) 
, REGISTER_TYPE VARCHAR2(3) 
, STRUCTURE VARCHAR2(3) 
, TYPE VARCHAR2(3) 
, CONSTRAINT LAG_LEVEL_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE TABLE GCM.LAG_SPATIAL_UNIT 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, LEVEL_ID VARCHAR2(48) 
, AREA NUMBER 
, AREA_TYPE VARCHAR2(3) 
, DIMENSION_TYPE VARCHAR2(3) 
, ADDRESS_ID VARCHAR2(48) 
, LABEL VARCHAR2(255) NOT NULL 
, REFERENCE_POINT MDSYS.SDO_GEOMETRY
, SURFACE_RELATION VARCHAR2(3) 
, VOLUME NUMBER 
, VOLUME_TYPE VARCHAR2(3) 
, LAND_USE VARCHAR2(3) 
, POLYGON MDSYS.SDO_GEOMETRY
, CONSTRAINT LAG_SPATIAL_UNIT_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.LAG_SUNIT_LOCAL_ID_IX ON GCM.LAG_SPATIAL_UNIT
(LOCAL_ID)
NOLOGGING
PCTFREE    5
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE TABLE GCM.EXT_ADM_USE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(255) 
, CONSTRAINT EXT_ADM_USE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.EXT_COUNTRY 
(
  CODE VARCHAR2(2) NOT NULL 
, NAME VARCHAR2(255) 
, CONSTRAINT EXT_COUNTRIES_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.EXT_LAND_USE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(255) 
, CONSTRAINT EXT_LAND_USE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.EXT_MUNICIPALITY 
(
  CODE VARCHAR2(16) NOT NULL 
, LOCAL_ID VARCHAR2(20) 
, NAME VARCHAR2(255) 
, CONSTRAINT EXT_MUNICIPALITY_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.EXT_STATE_PROVINCE 
(
  CODE VARCHAR2(8) NOT NULL 
, LOCAL_ID VARCHAR2(20) 
, NAME VARCHAR2(255) 
, CONSTRAINT EXT_STATE_PROVINCE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE INDEX GCM.EXT_SPROVINCE_IX ON GCM.EXT_STATE_PROVINCE
(LOCAL_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    15
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL; 

CREATE TABLE GCM.EXT_TAX_TYPE 
(
  CODE VARCHAR2(8) NOT NULL 
, DESCRIPTION VARCHAR2(255) 
, CONSTRAINT EXT_TAX_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.EXT_VALUATION_TYPE 
(
  CODE VARCHAR2(3) NOT NULL 
, DESCRIPTION VARCHAR2(255) 
, CONSTRAINT EXT_VALUATION_TYPE_PK PRIMARY KEY 
  (
    CODE 
  )
  ENABLE 
);

CREATE TABLE GCM.EXT_ADDRESS 
(
  OID VARCHAR2(48) NOT NULL 
, ADDRESS_COORDINATE SDO.SDO_GEOMETRY 
, ADDRESS_ID VARCHAR2(32) 
, STREET_NAME VARCHAR2(255) 
, BUILDING_NAME VARCHAR2(255) 
, BUILDING_NUMBER VARCHAR2(12) 
, POSTAL_CODE VARCHAR2(12) 
, POST_BOX VARCHAR2(12) 
, MUNICIPALITY VARCHAR2(16) 
, STATE_PROVINCE VARCHAR2(8) 
, COUNTRY VARCHAR2(2) 
, CONSTRAINT EXT_ADDRESS_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.EXT_ADDRESS_LOCAL_ID_IX ON GCM.EXT_ADDRESS
(ADDRESS_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    15
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL; 

CREATE TABLE GCM.EXT_TAXATION 
(
  OID VARCHAR2(48) NOT NULL 
, LOCAL_ID VARCHAR2(48) 
, BA_UNIT_ID VARCHAR2(48) 
, PARTY_ID VARCHAR2(48) 
, FISCAL_PERIOD VARCHAR2(12) 
, TAX_TYPE VARCHAR2(3) 
, TAX_DATE DATE 
, AMOUNT NUMBER 
, AMOUNT_PAID NUMBER 
, CONSTRAINT EXT_TAXATION_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE INDEX GCM.EXT_TAXATION_LOCAL_ID_IX ON GCM.EXT_TAXATION
(LOCAL_ID)
NOLOGGING
TABLESPACE INDX
PCTFREE    15
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL; 

CREATE TABLE GCM.EXT_VALUATION 
(
  OID VARCHAR2(48) NOT NULL 
, BA_UNIT_ID VARCHAR2(48) 
, PERIOD NUMBER(4) 
, VALUE NUMBER 
, VALUE_DATE DATE 
, VALUE_TYPE VARCHAR2(3) 
, CONSTRAINT EXT_VALUATION_PK PRIMARY KEY 
  (
    OID 
  )
  ENABLE 
);

CREATE UNIQUE INDEX GCM.EXT_VALUATION_AK ON GCM.EXT_VALUATION
(BA_UNIT_ID, PERIOD)
NOLOGGING
TABLESPACE INDX
PCTFREE    15
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL; 

-------------------------------------------------------------------------------------------------------
-- CREACIÓN DE RELACIONES DE CLAVES FORÁNEAS
-------------------------------------------------------------------------------------------------------
ALTER TABLE GCM.LAG_ADM_SOURCE
ADD CONSTRAINT LAG_ASOURCE_ASTATUSTYPE_FK FOREIGN KEY
(
  AVAIL_STATUS 
)
REFERENCES GCM.LAG_AVAIL_STATUS_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_ADM_SOURCE
ADD CONSTRAINT LAG_ASOURCE_PFORMCODE_FK FOREIGN KEY
(
  MAIN_TYPE 
)
REFERENCES GCM.CI_PRES_FORM_CODE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_ADM_SOURCE
ADD CONSTRAINT LAG_ASOURCE_RESPONSABLE_FK FOREIGN KEY
(
  SOURCE 
)
REFERENCES GCM.CI_RESPONSABLE_PARTY
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_BA_UNIT
ADD CONSTRAINT LAG_BA_UNIT_ADM_USE_FK FOREIGN KEY
(
  ADM_USE 
)
REFERENCES GCM.EXT_ADM_USE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_BA_UNIT
ADD CONSTRAINT LAG_BA_UNIT_SUNIT_FK FOREIGN KEY
(
  SUNIT_ID 
)
REFERENCES GCM.LAG_SPATIAL_UNIT
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_BA_UNIT
ADD CONSTRAINT LAG_BA_UNIT_TYPE_FK FOREIGN KEY
(
  BA_UNIT_TYPE 
)
REFERENCES GCM.LAG_BA_UNIT_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LAG_RIGHT_ASOURCE_FK FOREIGN KEY
(
  SOURCE_ID 
)
REFERENCES GCM.LAG_ADM_SOURCE
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LA_RIGHT_BA_UNIT_FK FOREIGN KEY
(
  BAUNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LA_RIGHT_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_RIGHT
ADD CONSTRAINT LA_RIGHT_TYPE_FK FOREIGN KEY
(
  RIGHT_TYPE 
)
REFERENCES GCM.LAG_RIGHT_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_CROPS
ADD CONSTRAINT LA_CROPS_BA_UNIT_FK FOREIGN KEY
(
  BAUNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_CROPS
ADD CONSTRAINT LA_CROPS_TYPE_FK FOREIGN KEY
(
  CROP_TYPE 
)
REFERENCES GCM.LAG_CROPS_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_GROUP_PARTY
ADD CONSTRAINT LAG_GROUP_PARTY_PARTY_FK FOREIGN KEY
(
  OID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_PARTY
ADD CONSTRAINT LAG_PARTY_ADDRESS_FK FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES GCM.EXT_ADDRESS
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_PARTY
ADD CONSTRAINT LAG_PARTY_ROLE_FK FOREIGN KEY
(
  PARTY_ROLE 
)
REFERENCES GCM.LAG_PARTY_ROLE_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_PARTY
ADD CONSTRAINT LAG_PARTY_TYPE_FK FOREIGN KEY
(
  PARTY_TYPE 
)
REFERENCES GCM.LAG_PARTY_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_PARTY_MEMBER
ADD CONSTRAINT LAG_PARTY_MEMBER_FK FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES GCM.LAG_GROUP_PARTY
(
  OID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE GCM.LAG_PARTY_MEMBER
ADD CONSTRAINT LAG_PARTY_MEMBER_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE GCM.LAG_LEVEL
ADD CONSTRAINT LAG_LEVEL_CONTENT_FK FOREIGN KEY
(
  TYPE 
)
REFERENCES GCM.LAG_LEVEL_CONTENT_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_LEVEL
ADD CONSTRAINT LAG_LEVEL_REGISTER_FK FOREIGN KEY
(
  REGISTER_TYPE 
)
REFERENCES GCM.LAG_REGISTER_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_LEVEL
ADD CONSTRAINT LAG_LEVEL_STRUCTURE_FK FOREIGN KEY
(
  STRUCTURE 
)
REFERENCES GCM.LAG_STRUCTURE_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_ADDRESS_FK FOREIGN KEY
(
  ADDRESS_ID 
)
REFERENCES GCM.EXT_ADDRESS
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_AREA_FK FOREIGN KEY
(
  AREA_TYPE 
)
REFERENCES GCM.LAG_AREA_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_DIMENSION_FK FOREIGN KEY
(
  DIMENSION_TYPE 
)
REFERENCES GCM.LAG_DIMENSION_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_LAND_USE_FK FOREIGN KEY
(
  LAND_USE 
)
REFERENCES GCM.EXT_LAND_USE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_LEVEL_FK FOREIGN KEY
(
  LEVEL_ID 
)
REFERENCES GCM.LAG_LEVEL
(
  OID 
)
ENABLE;

ALTER TABLE GCM.LAG_SPATIAL_UNIT
ADD CONSTRAINT LAG_SUNIT_VOLUME_FK FOREIGN KEY
(
  VOLUME_TYPE 
)
REFERENCES GCM.LAG_VOLUME_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.EXT_ADDRESS
ADD CONSTRAINT EXT_ADDRESS_COUNTRY_FK FOREIGN KEY
(
  COUNTRY 
)
REFERENCES GCM.EXT_COUNTRY
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.EXT_ADDRESS
ADD CONSTRAINT EXT_ADDRESS_MUNICIPALITY_FK FOREIGN KEY
(
  MUNICIPALITY 
)
REFERENCES GCM.EXT_MUNICIPALITY
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.EXT_ADDRESS
ADD CONSTRAINT EXT_ADDRESS_STATE_PROVINCE_FK FOREIGN KEY
(
  STATE_PROVINCE 
)
REFERENCES GCM.EXT_STATE_PROVINCE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.EXT_TAXATION
ADD CONSTRAINT EXT_TAXATION_BA_UNIT_FK FOREIGN KEY
(
  BA_UNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
)
ENABLE;

ALTER TABLE GCM.EXT_TAXATION
ADD CONSTRAINT EXT_TAXATION_PARTY_FK FOREIGN KEY
(
  PARTY_ID 
)
REFERENCES GCM.LAG_PARTY
(
  OID 
)
ENABLE;

ALTER TABLE GCM.EXT_TAXATION
ADD CONSTRAINT EXT_TAXATION_TAX_TYPE_FK FOREIGN KEY
(
  TAX_TYPE 
)
REFERENCES GCM.EXT_TAX_TYPE
(
  CODE 
)
ENABLE;

ALTER TABLE GCM.EXT_VALUATION
ADD CONSTRAINT EXT_VALUATION_BA_UNIT_FK FOREIGN KEY
(
  BA_UNIT_ID 
)
REFERENCES GCM.LAG_BA_UNIT
(
  OID 
)
ENABLE;

ALTER TABLE GCM.EXT_VALUATION
ADD CONSTRAINT EXT_VALUATION_VAL_TYPE_FK FOREIGN KEY
(
  VALUE_TYPE 
)
REFERENCES GCM.EXT_VALUATION_TYPE
(
  CODE 
)
ENABLE;

--------------------------------------------------------------------------------------------------------
-- CÓDIGO PLSQL Y VISTAS DE DATOS
--------------------------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION GCM.GUID RETURN VARCHAR2 
IS
   GUID VARCHAR2(100);
BEGIN
   SELECT LOWER(SYS_GUID()) INTO GUID FROM DUAL;

   RETURN SUBSTR(GUID, 1, 8) || '-' || SUBSTR(GUID, 9, 4) || '-' || SUBSTR(GUID, 13, 4) || '-' || SUBSTR(GUID, 17, 4) || '-' || SUBSTR(GUID, -12);
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_CI_RESPONSABLE_PARTY
BEFORE INSERT ON GCM.CI_RESPONSABLE_PARTY 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_EXT_ADDRESS
BEFORE INSERT ON GCM.EXT_ADDRESS 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_EXT_TAXATION
BEFORE INSERT ON GCM.EXT_TAXATION 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_EXT_VALUATION
BEFORE INSERT ON GCM.EXT_VALUATION 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_ADM_SOURCE
BEFORE INSERT ON GCM.LAG_ADM_SOURCE 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_BA_UNIT
BEFORE INSERT ON GCM.LAG_BA_UNIT 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_GROUP_PARTY
BEFORE INSERT ON GCM.LAG_GROUP_PARTY
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_LEVEL
BEFORE INSERT ON GCM.LAG_LEVEL
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_PARTY
BEFORE INSERT ON GCM.LAG_PARTY
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_RIGHT
BEFORE INSERT ON GCM.LAG_RIGHT
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_CROPS
BEFORE INSERT ON GCM.LAG_CROPS 
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

CREATE OR REPLACE TRIGGER GCM.TR_LAG_SPATIAL_UNIT
BEFORE INSERT ON GCM.LAG_SPATIAL_UNIT
FOR EACH ROW
BEGIN
   -- SI EL IDENTIFICADOR GLOBAL ES NULO ASIGNAMOS UN GUID POR DEFECTO...
   :NEW.OID := NVL(:NEW.OID, GUID());
END;
/

----------------------------------------------------------
-- VISTA DE VALORES CATASTRALES DE LAS UNIDADES BÁSICAS --
----------------------------------------------------------
CREATE OR REPLACE VIEW GCM.VW_EXT_CUR_VALUATION AS
SELECT BU.OID, BU.LOCAL_ID, EV.PERIOD, EV.VALUE, EV.VALUE_DATE, 
       EV.VALUE_TYPE, EVT.DESCRIPTION AS VALUE_TYPE_DESC
FROM
 (SELECT BA_UNIT_ID, MAX(PERIOD) AS LAST_PERIOD
  FROM GCM.EXT_VALUATION GROUP BY BA_UNIT_ID) LAST_VAL,
 GCM.LAG_BA_UNIT BU, GCM.EXT_VALUATION EV, GCM.EXT_VALUATION_TYPE EVT
WHERE BU.OID=LAST_VAL.BA_UNIT_ID AND EV.BA_UNIT_ID=LAST_VAL.BA_UNIT_ID AND 
      EV.PERIOD=LAST_VAL.LAST_PERIOD AND EVT.CODE(+)=EV.VALUE_TYPE; 

------------------------
-- VISTA DE IMPUESTOS --
------------------------
CREATE OR REPLACE VIEW GCM.VW_EXT_CUR_TAXATION AS
SELECT BU.OID, BU.LOCAL_ID, ET.FISCAL_PERIOD, ET.TAX_TYPE, ETT.DESCRIPTION AS TAX_TYPE_DESC, ET.TAX_DATE,
       ET.AMOUNT, ET.AMOUNT_PAID, DECODE(ET.AMOUNT, 0, 0, ROUND((ET.AMOUNT_PAID / ET.AMOUNT) * 100, 2)) AS PERCENT_PAID
FROM
 (SELECT BA_UNIT_ID, MAX(FISCAL_PERIOD) AS LAST_PERIOD
  FROM GCM.EXT_TAXATION GROUP BY BA_UNIT_ID) LAST_TAX,
 GCM.LAG_BA_UNIT BU, GCM.EXT_TAXATION ET, GCM.EXT_TAX_TYPE ETT
WHERE BU.OID=LAST_TAX.BA_UNIT_ID AND ET.BA_UNIT_ID=LAST_TAX.BA_UNIT_ID AND 
      ET.FISCAL_PERIOD=LAST_TAX.LAST_PERIOD AND ETT.CODE(+)=ET.TAX_TYPE; 

---------------------------------------------------
-- VISTA DE LAS UNIDADES BÁSICAS ADMINISTRATIVAS --
---------------------------------------------------
CREATE OR REPLACE VIEW GCM.VW_BA_UNIT
AS
SELECT B.OID, B.LOCAL_ID, B.BA_UNIT_TYPE, BUT.DESCRIPTION AS BA_UNIT_TYPE_DESCRIP,
       B.PLACE_NAME, SU.LOCAL_ID AS SUNIT_LOCAL_ID, SU.AREA, SU.AREA_TYPE, 
       LAT.DESCRIPTION AS AREA_TYPE_DESCRIP, SU.DIMENSION_TYPE, LDT.DESCRIPTION AS DIMENSION_TYPE_DESCRIP, 
       SU.LABEL AS SPATIAL_UNIT_DESCRIP, SU.LAND_USE, ELU.DESCRIPTION AS LAND_USE_DESCRIP, B.ADM_USE, 
       EAU.DESCRIPTION AS ADM_USE_DESCRIP, EV.VALUE, EV.VALUE_DATE, EV.VALUE_TYPE, EV.VALUE_TYPE_DESC,
       EA.ADDRESS_ID, EA.STREET_NAME, EA.BUILDING_NAME, EA.BUILDING_NUMBER, EA.POSTAL_CODE, EA.POST_BOX, 
       EM.LOCAL_ID AS MUN_CODE, EM.NAME MUN_NAME, ESP.LOCAL_ID AS SP_CODE, ESP.NAME AS SP_NAME,
       EC.CODE AS COUNTRY_CODE, EC.NAME AS COUNTRY_NAME   
FROM GCM.LAG_BA_UNIT B, GCM.LAG_BA_UNIT_TYPE BUT, GCM.LAG_SPATIAL_UNIT SU, 
     GCM.LAG_AREA_TYPE LAT, GCM.LAG_DIMENSION_TYPE LDT, GCM.EXT_ADDRESS EA,
     GCM.EXT_MUNICIPALITY EM, GCM.EXT_STATE_PROVINCE ESP, GCM.EXT_COUNTRY EC,
     GCM.EXT_LAND_USE ELU, GCM.EXT_ADM_USE EAU, GCM.VW_EXT_CUR_VALUATION EV
WHERE BUT.CODE(+)=B.BA_UNIT_TYPE AND SU.OID(+)=B.SUNIT_ID AND LAT.CODE(+)=SU.AREA_TYPE AND 
      LDT.CODE(+)=SU.DIMENSION_TYPE AND EA.OID(+)=SU.ADDRESS_ID AND EM.CODE(+)=EA.MUNICIPALITY AND 
      ESP.CODE(+)=EA.STATE_PROVINCE AND EC.CODE(+)=EA.COUNTRY AND ELU.CODE(+)=SU.LAND_USE AND 
      EAU.CODE(+)=B.ADM_USE AND EV.OID(+)=B.OID;

-----------------------------------------------------------
-- VISTA DE DERECHOS DE PROPIEDAD SOBRE UNIDADES BÁSICAS --
-----------------------------------------------------------
CREATE OR REPLACE VIEW GCM.VW_RIGHT AS
SELECT R.OID, R.LOCAL_ID, R.RIGHT_TYPE, RT.DESCRIPTION RIGHT_TYPE_DESC, R.SHARES, R.PARTY_ID, 
       P.LOCAL_ID PARTY_LOCAL_ID, P.NAME PARTY_NAME, P.PARTY_ROLE, PT.DESCRIPTION PARTY_ROLE_DESC, 
       EA.ADDRESS_ID PARTY_ADDRESS_ID, EA.STREET_NAME PARTY_STREET_NAME, EA.BUILDING_NAME PARTY_BUILDING_NAME, 
       EA.BUILDING_NUMBER PARTY_BUILDING_NUMBER, EA.POSTAL_CODE PARTY_POSTAL_CODE, EA.POST_BOX PARTY_POST_BOX, 
       EM.LOCAL_ID PARTY_MUN_CODE, EM.NAME PARTY_MUN_NAME, ESP.LOCAL_ID PARTY_SP_CODE, ESP.NAME PARTY_SP_NAME, 
       EC.CODE PARTY_COUNTRY_CODE, EC.NAME PARTY_COUNTRY_NAME
FROM GCM.LAG_RIGHT R, GCM.LAG_RIGHT_TYPE RT, GCM.LAG_PARTY P,
     GCM.LAG_PARTY_ROLE_TYPE PT, GCM.EXT_ADDRESS EA,
     GCM.EXT_MUNICIPALITY EM, GCM.EXT_STATE_PROVINCE ESP, GCM.EXT_COUNTRY EC
WHERE RT.CODE(+) = R.RIGHT_TYPE AND P.OID(+)=R.PARTY_ID AND 
      PT.CODE(+)=P.PARTY_ROLE AND EA.OID(+)=P.ADDRESS_ID AND EM.CODE(+)=EA.MUNICIPALITY AND 
      ESP.CODE(+)=EA.STATE_PROVINCE AND EC.CODE(+)=EA.COUNTRY;

------------------------
-- VISTA DE CULTIVOS  --
------------------------
CREATE OR REPLACE VIEW GCM.VW_CROPS
AS
SELECT CU.OID, CU.LOCAL_ID, CU.CROP_TYPE, NVL(TC.DESCRIPTION, 'CULTIVO ' || CU.CROP_TYPE) AS CROP_TYPE_DESC, CU.AREA, CU.ECONOMIC_VALUE   
FROM GCM.LAG_CROPS CU, GCM.LAG_CROPS_TYPE TC
WHERE TC.CODE(+)=CU.CROP_TYPE;

-----------------------------------
-- VISTA DE UNIDADES ESPACIALES  --
-----------------------------------
CREATE OR REPLACE VIEW GCM.VW_SPATIAL_UNIT
AS
SELECT SU.OID, SU.LOCAL_ID, SU.AREA, SU.AREA_TYPE, LAT.DESCRIPTION AS AREA_TYPE_DESCRIP, SU.DIMENSION_TYPE, 
       LDT.DESCRIPTION AS DIMENSION_TYPE_DESCRIP, SU.LABEL AS SPATIAL_UNIT_DESCRIP, SU.LAND_USE, 
       ELU.DESCRIPTION AS LAND_USE_DESCRIP, EA.ADDRESS_ID, EA.STREET_NAME, EA.BUILDING_NAME, EA.BUILDING_NUMBER, 
       EA.POSTAL_CODE, EA.POST_BOX, EM.LOCAL_ID AS MUN_CODE, EM.NAME MUN_NAME, ESP.LOCAL_ID AS SP_CODE, 
       ESP.NAME AS SP_NAME, EC.CODE AS COUNTRY_CODE, EC.NAME AS COUNTRY_NAME, 
       VAL.TOTAL_VALUE, TAX.TOTAL_AMOUNT, TAX.TOTAL_PAID, TAX.PERCENT_PAID, CROP.CROP_TYPE, CROP.CROP_DESCRIP, 
       SU.POLYGON,
       SDO_CS.TRANSFORM(NVL(SU.REFERENCE_POINT, SDO_GEOM.SDO_CENTROID(SU.POLYGON, 0.05)), 8307).SDO_POINT.Y AS LATITUDE, 
       SDO_CS.TRANSFORM(NVL(SU.REFERENCE_POINT, SDO_GEOM.SDO_CENTROID(SU.POLYGON, 0.05)), 8307).SDO_POINT.X AS LONGITUDE
FROM GCM.LAG_SPATIAL_UNIT SU, GCM.LAG_AREA_TYPE LAT, GCM.LAG_DIMENSION_TYPE LDT, 
     GCM.EXT_ADDRESS EA, GCM.EXT_MUNICIPALITY EM, GCM.EXT_STATE_PROVINCE ESP, 
     GCM.EXT_COUNTRY EC, GCM.EXT_LAND_USE ELU, 
     (SELECT MAIN_CROP.SUNIT_ID, MAIN_CROP.CROP_TYPE, CT.DESCRIPTION AS CROP_DESCRIP
      FROM 
       (SELECT BU.SUNIT_ID, CR.CROP_TYPE,
               RANK() OVER(PARTITION BY SUNIT_ID ORDER BY SUM(AREA) DESC) AS RNK
        FROM GCM.LAG_CROPS CR, GCM.LAG_BA_UNIT BU
        WHERE BU.OID=CR.BAUNIT_ID
        GROUP BY BU.SUNIT_ID, CR.CROP_TYPE) MAIN_CROP, GCM.LAG_CROPS_TYPE CT
        WHERE MAIN_CROP.RNK=1 AND CT.CODE=MAIN_CROP.CROP_TYPE) CROP,
     (SELECT SU.OID, SUM(VALUE) AS TOTAL_VALUE
      FROM GCM.VW_EXT_CUR_VALUATION CV, GCM.LAG_BA_UNIT BU, GCM.LAG_SPATIAL_UNIT SU
      WHERE BU.OID=CV.OID AND SU.OID=BU.SUNIT_ID
      GROUP BY SU.OID) VAL,
     (SELECT SU.OID, SUM(AMOUNT) AS TOTAL_AMOUNT, SUM(AMOUNT_PAID) AS TOTAL_PAID, ROUND(AVG(PERCENT_PAID),2) AS PERCENT_PAID
      FROM GCM.VW_EXT_CUR_TAXATION CT, GCM.LAG_BA_UNIT BU, GCM.LAG_SPATIAL_UNIT SU
      WHERE BU.OID=CT.OID AND SU.OID=BU.SUNIT_ID
      GROUP BY SU.OID) TAX
WHERE LAT.CODE(+)=SU.AREA_TYPE AND LDT.CODE(+)=SU.DIMENSION_TYPE AND EA.OID(+)=SU.ADDRESS_ID AND 
      EM.CODE(+)=EA.MUNICIPALITY AND ESP.CODE(+)=EA.STATE_PROVINCE AND EC.CODE(+)=EA.COUNTRY AND 
      ELU.CODE(+)=SU.LAND_USE AND CROP.SUNIT_ID(+)=SU.OID AND VAL.OID(+)=SU.OID AND TAX.OID(+)=SU.OID;

--------------------------------------------------------------------------------------------------------
-- COMENTARIOS DE COLUMNAS
--------------------------------------------------------------------------------------------------------
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.OID IS 'Codigo Unico Global';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.INDIVIDUAL_NAME IS 'Nombre del Responsable';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.ORGANIZATION_NAME IS 'Nombre de la Organizacion responsable';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.POSITION_NAME IS 'Cargo de la Persona responsable';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.ADDRESS IS 'Direccion de contacto';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.EMAIL IS 'Correo Electronico';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.PHONE_NUMBER IS 'Numero de Telefono de contacto';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.FAX_NUMBER IS 'Numero de Fax de contacto';
COMMENT ON COLUMN GCM.CI_RESPONSABLE_PARTY.ROLE IS 'Funcion realizada por la parte responsable';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.DESCRIPTION IS 'Descripcion del Documento';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.SOURCE_TYPE IS 'Tipo de Documento de fuente administrativa';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.TRANSACTION_CODE IS 'Codigo Registral/Documental de la transaccion';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.ACCEPTANCE IS 'Fecha de Vigencia de la Ley de la fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.AVAIL_STATUS IS 'Estado de Disponibilidad';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.EXT_ARCHIVE_ID IS 'Identificador de la fuente en un registro externo';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.LIFE_SPAN_STAMP IS 'Fecha de inicio de validez de la fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.MAIN_TYPE IS 'Tipo de Documento';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.QUALITY IS 'Calidad de la Fuente (DQ_Element ISO 19115)';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.RECORDATION IS 'Fecha de Registro de la fuente por la Autoridad';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.SOURCE IS 'Responsable de la Fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.SUBMISSION IS 'Fecha de Presentacion de la Fuente';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE.OFFICIAL IS 'Si es un documento oficial';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_ADM_SOURCE_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_AVAIL_STATUS_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_AVAIL_STATUS_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.BA_UNIT_TYPE IS 'Tipo';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.PLACE_NAME IS 'Nombre Toponimico';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.SUNIT_ID IS 'Identificador de Unidad Espacial';
COMMENT ON COLUMN GCM.LAG_BA_UNIT.ADM_USE IS 'Uso Economico/Administrativo de la Unidad';
COMMENT ON COLUMN GCM.LAG_BA_UNIT_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_BA_UNIT_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.CI_PRES_FORM_CODE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.CI_PRES_FORM_CODE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_RIGHT.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_RIGHT.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_RIGHT.BAUNIT_ID IS 'Identificador de la Unidad Administrativa';
COMMENT ON COLUMN GCM.LAG_RIGHT.PARTY_ID IS 'Identificador del Interesado';
COMMENT ON COLUMN GCM.LAG_RIGHT.SOURCE_ID IS 'Identificador de la fuente administrativa del Derecho';
COMMENT ON COLUMN GCM.LAG_RIGHT.DESCRIPCION IS 'Descripcion del Derecho';
COMMENT ON COLUMN GCM.LAG_RIGHT.RIGHT_TYPE IS 'Tipo de Derecho';
COMMENT ON COLUMN GCM.LAG_RIGHT.SHARES IS 'Cuota de Participacion';
COMMENT ON COLUMN GCM.LAG_RIGHT.SHARE_CHECK IS 'Indicada si la participacion es compartida';
COMMENT ON COLUMN GCM.LAG_RIGHT.TIME_SPEC IS 'Periodo de vigencia (si existe) del derecho (ISO 8601).';
COMMENT ON COLUMN GCM.LAG_RIGHT_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_RIGHT_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_CROPS.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.LAG_CROPS.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_CROPS.BAUNIT_ID IS 'Identificador de la BAUnit matriz del Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.CROP_TYPE IS 'Tipo de Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.AREA IS 'Superficie del Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.ECONOMIC_VALUE IS 'Valor Economico del Cultivo';
COMMENT ON COLUMN GCM.LAG_CROPS.POLYGON IS 'Geometria del tipo poligonal';
COMMENT ON COLUMN GCM.LAG_CROPS_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_CROPS_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_GROUP_PARTY.OID IS 'Identificador del Grupo de Interesados';
COMMENT ON COLUMN GCM.LAG_GROUP_PARTY.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_GROUP_PARTY.GROUP_PARTY_TYPE IS 'Tipo de Grupo de Interesados';
COMMENT ON COLUMN GCM.LAG_PARTY.OID IS 'Identificador único de interesado';
COMMENT ON COLUMN GCM.LAG_PARTY.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_PARTY.NAME IS 'Nombre del Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY.PARTY_ROLE IS 'Rol de interesado en el proceso de actualizacion y mantenimiento';
COMMENT ON COLUMN GCM.LAG_PARTY.PARTY_TYPE IS 'Tipo de Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY.ADDRESS_ID IS 'Identificador de Direccion Postal';
COMMENT ON COLUMN GCM.LAG_PARTY_MEMBER.GROUP_ID IS 'Identificador del Grupo de Interesados';
COMMENT ON COLUMN GCM.LAG_PARTY_MEMBER.PARTY_ID IS 'Identificador del Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY_MEMBER.PART IS 'Porcentaje de Participacion (0..1)';
COMMENT ON COLUMN GCM.LAG_PARTY_ROLE_TYPE.CODE IS 'Codigo de Rol';
COMMENT ON COLUMN GCM.LAG_PARTY_ROLE_TYPE.DESCRIPTION IS 'Descripcion del Rol';
COMMENT ON COLUMN GCM.LAG_PARTY_TYPE.CODE IS 'Código de Tipo de Interesado';
COMMENT ON COLUMN GCM.LAG_PARTY_TYPE.DESCRIPTION IS 'Descripcion del Tipo de Interesado';
COMMENT ON COLUMN GCM.LAG_AREA_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_AREA_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_DIMENSION_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_DIMENSION_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_LEVEL.OID IS 'Identificador unico de interesado';
COMMENT ON COLUMN GCM.LAG_LEVEL.NAME IS 'Nombre del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL.REGISTER_TYPE IS 'Tipo de Registro del contenido del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL.STRUCTURE IS 'Estructura de la geometria del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL.TYPE IS 'Tipo de contenido del Nivel';
COMMENT ON COLUMN GCM.LAG_LEVEL_CONTENT_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_LEVEL_CONTENT_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_REGISTER_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_REGISTER_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.OID IS 'Identificador Único Global';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LEVEL_ID IS 'Identificador de Nivel';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.AREA IS 'Area de la Unidad Espacial';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.AREA_TYPE IS 'Tipo de Area';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.DIMENSION_TYPE IS 'Dimension del Area';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.ADDRESS_ID IS 'Identificador de Direccion Postal';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LABEL IS 'Descripcion textual de la Undad Espacial';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.REFERENCE_POINT IS 'Coordenada de un punto dentro de la Unidad Espacial';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.SURFACE_RELATION IS 'Indica cuando la unidad espacial está por encima o por debajo de la superficie.';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.VOLUME IS 'Volumen de la Unidad Espacial en m3';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.VOLUME_TYPE IS 'Tipo de Volumen';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.LAND_USE IS 'Tipo de Uso del Suelo';
COMMENT ON COLUMN GCM.LAG_SPATIAL_UNIT.POLYGON IS 'Geometria del tipo poligonal';
COMMENT ON COLUMN GCM.LAG_STRUCTURE_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_STRUCTURE_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_SURFACE_RELATION_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_SURFACE_RELATION_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON COLUMN GCM.LAG_VOLUME_TYPE.CODE IS 'Codigo';
COMMENT ON COLUMN GCM.LAG_VOLUME_TYPE.DESCRIPTION IS 'Descripcion';
COMMENT ON TABLE GCM.EXT_ADM_USE IS 'Uso de la Unidad Basica Administrativa';
COMMENT ON COLUMN GCM.EXT_ADDRESS.OID IS 'Identificdor Unico Global';
COMMENT ON COLUMN GCM.EXT_ADDRESS.ADDRESS_COORDINATE IS 'Coordenada de la Direccion Postal Externa';
COMMENT ON COLUMN GCM.EXT_ADDRESS.ADDRESS_ID IS 'Identificador de la Direccion Postal Externa';
COMMENT ON COLUMN GCM.EXT_ADDRESS.STREET_NAME IS 'Nombre de la Calle';
COMMENT ON COLUMN GCM.EXT_ADDRESS.BUILDING_NAME IS 'Nombre del Edificio';
COMMENT ON COLUMN GCM.EXT_ADDRESS.BUILDING_NUMBER IS 'Numero del Edificio';
COMMENT ON COLUMN GCM.EXT_ADDRESS.POSTAL_CODE IS 'Codigo Postal';
COMMENT ON COLUMN GCM.EXT_ADDRESS.POST_BOX IS 'Apartado de Correos';
COMMENT ON COLUMN GCM.EXT_ADDRESS.MUNICIPALITY IS 'Codigo de Municipio/Ciudad';
COMMENT ON COLUMN GCM.EXT_ADDRESS.STATE_PROVINCE IS 'Codigo de Estado/Departamento/Provincia';
COMMENT ON COLUMN GCM.EXT_ADDRESS.COUNTRY IS 'Codigo de Pais';
COMMENT ON COLUMN GCM.EXT_ADM_USE.CODE IS 'Codigo de Uso';
COMMENT ON COLUMN GCM.EXT_ADM_USE.DESCRIPTION IS 'Descripcion del Uso';
COMMENT ON COLUMN GCM.EXT_COUNTRY.CODE IS 'Codigo de Pais según ISO 3166-1';
COMMENT ON COLUMN GCM.EXT_COUNTRY.NAME IS 'Nombre del Pais';
COMMENT ON COLUMN GCM.EXT_LAND_USE.CODE IS 'Codigo de Tipo de Uso del Suelo';
COMMENT ON COLUMN GCM.EXT_LAND_USE.DESCRIPTION IS 'Descripcion del tipo de Uso del Suelo';
COMMENT ON COLUMN GCM.EXT_MUNICIPALITY.CODE IS 'Codigo de Municipio';
COMMENT ON COLUMN GCM.EXT_MUNICIPALITY.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.EXT_MUNICIPALITY.NAME IS 'Nombre del Municipio';
COMMENT ON COLUMN GCM.EXT_STATE_PROVINCE.CODE IS 'Codigo de Estado/Departamento/Provincia según ISO 3166-2';
COMMENT ON COLUMN GCM.EXT_STATE_PROVINCE.LOCAL_ID IS 'Identificador Local/Legal';
COMMENT ON COLUMN GCM.EXT_STATE_PROVINCE.NAME IS 'Nombre del Estado/Departamento/Provincia';
COMMENT ON COLUMN GCM.EXT_TAXATION.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.EXT_TAXATION.LOCAL_ID IS 'Referencia Local del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.BA_UNIT_ID IS 'Identificador de la BAUnit asociada al Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.PARTY_ID IS 'Identificador del Interesado';
COMMENT ON COLUMN GCM.EXT_TAXATION.FISCAL_PERIOD IS 'Ejercicio Fiscal';
COMMENT ON COLUMN GCM.EXT_TAXATION.TAX_TYPE IS 'Tipo del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.TAX_DATE IS 'Fecha del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.AMOUNT IS 'Importe del Impuesto';
COMMENT ON COLUMN GCM.EXT_TAXATION.AMOUNT_PAID IS 'Cantidad Pagada';
COMMENT ON COLUMN GCM.EXT_TAX_TYPE.CODE IS 'Codigo de Tipo de Impuesto/Tasa';
COMMENT ON COLUMN GCM.EXT_TAX_TYPE.DESCRIPTION IS 'Descripcion del Impuesto/Tasa';
COMMENT ON COLUMN GCM.EXT_VALUATION.OID IS 'Identificador Unico Global';
COMMENT ON COLUMN GCM.EXT_VALUATION.BA_UNIT_ID IS 'Identificador de Unidad Administrativa valorada';
COMMENT ON COLUMN GCM.EXT_VALUATION.PERIOD IS 'Período en el que rige la valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION.VALUE IS 'Valoracion de la Unidad Administrativa';
COMMENT ON COLUMN GCM.EXT_VALUATION.VALUE_DATE IS 'Fecha de la Valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION.VALUE_TYPE IS 'Tipo de Valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION_TYPE.CODE IS 'Codigo de Tipo de Valoracion';
COMMENT ON COLUMN GCM.EXT_VALUATION_TYPE.DESCRIPTION IS 'Descripcion del Tipo de Valoracion';

EXIT;
